name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the Borum Classroom GitHub! Make sure you are using an issue template when opening issues'
        pr-message: 'Welcome to the Borum Classroom GitHub! Make sure you are using the pull request template and have written passing tests if applicable. '
